use_frameworks!

target 'ExcelCollectionView_Example' do
  pod 'ExcelCollectionView', :path => '../'

  target 'ExcelCollectionView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
